FROM python:3.6-slim-buster

COPY requirements.txt .

RUN pip --no-cache-dir install -r requirements.txt --ignore-installed six

COPY . .

EXPOSE 80

ENV FLASK_APP=main.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]

