# FROM alpine:latest

# RUN apk update
# RUN apk add py-pip 
# RUN apk add --no-cache postgresql-dev gcc python3-dev musl-dev
# RUN pip install --upgrade pip

# WORKDIR /main
# COPY . /main
# RUN pip --no-cache-dir install -r requirements.txt --ignore-installed six
# EXPOSE 80
# ENV FLASK_APP=main.py
# CMD ["flask", "run", "--host=0.0.0.1", "--port=80"]


FROM python:3.6-slim-buster

COPY requirements.txt .

RUN pip --no-cache-dir install -r requirements.txt --ignore-installed six

COPY . .

EXPOSE 80

ENV FLASK_APP=main.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=80"]
